language: julia

os: linux
dist: bionic

julia:
  - 1.4
  - 1.5

script:
  - julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.test(coverage=true);'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'